load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "b7adb62e240353986bd399f0dd027c0b9c3fa73c6dc5541b1540ee55433b41a2",
    strip_prefix = "rules_jvm_external-dcf538185ec95de79f099a183ab4fc888edc6051",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/dcf538185ec95de79f099a183ab4fc888edc6051.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.1.1-jre",
        "junit:junit:4.13.2",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
