load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "c84d4a86e6b921851f4fb2894cbe7ae841d9d626f1e3fcd3705d58973d991c5f",
    strip_prefix = "rules_jvm_external-ae4da88339cec0dccdddae99ddf22eedfa3fad94",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/ae4da88339cec0dccdddae99ddf22eedfa3fad94.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.1.1-jre",
        "junit:junit:4.13.2",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
