load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "6db03cb42d22db490917a7db66179c32ff534cf5eea7efd42313e1160198e86a",
    strip_prefix = "rules_jvm_external-91f182919cb785802fcce08047b7a5cd86c46f4c",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/91f182919cb785802fcce08047b7a5cd86c46f4c.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.guava:guava:30.1.1-jre",
        "junit:junit:4.13.2",
        "org.hamcrest:hamcrest-all:1.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
